"use client";
import Link from "next/link";
import "../src/app/globals.css";
import Footer from "@/app/components/footer";

export default function TramsAndCondition() {
  return (
    <div className="bg-gray-900 max-w-[1600px] mx-auto text-white py-10 px-4">
      <div className="text-center py-2">
        <h1 className="text-xxl font-bold">Trams & Comdition</h1>
      </div>
      <div className="space-y-10 px-4 text-justify">
        <section>
          <h2 className="text-3xl font-semibold">Last updated: [{}]</h2>
          <p className="mt-4">
            At RATAN MATKA, we value your privacy and are committed to
            protecting your personal information. This Privacy Policy outlines
            our practices regarding the collection, use, and disclosure of your
            information when you use our services. By using our services, you
            agree to the collection and use of information in accordance with
            this Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">
            Interpretation and Definitions
          </h2>
          <h3 className="text-xl font-semibold mt-4">Interpretation</h3>
          <p className="mt-2">
            The words with initial capital letters have specific meanings
            defined below. These definitions apply whether they appear in
            singular or plural form.
          </p>
          <h3 className="text-xl font-semibold mt-4">Definitions</h3>
          <ul className="list-disc list-inside mt-2 space-y-2">
            <li>
              <strong>Account:</strong> A unique account created for you to
              access our service or parts of our service.
            </li>
            <li>
              <strong>Affiliate:</strong> An entity that controls, is controlled
              by, or is under common control with a party, where
              &quot;control&quot; means ownership of 50% or more of the shares,
              equity interest, or other securities entitled to vote for the
              election of directors or other managing authority.
            </li>
            <li>
              <strong>Company:</strong> Referred to as either &quot;the
              Company,&quot; &quot;We,&quot; &quot;Us,&quot; or &quot;Our&quot;
              in this Agreement, refers to RATAN MATKA.
            </li>
            <li>
              <strong>Cookies:</strong> Small files placed on your computer,
              mobile device, or any other device by a website, containing
              details of your browsing history on that website.
            </li>
            <li>
              <strong>Country:</strong> Refers to Karnataka, India.
            </li>
            <li>
              <strong>Device:</strong> Any device that can access the service,
              such as a computer, cellphone, or digital tablet.
            </li>
            <li>
              <strong>Personal Data:</strong> Any information that relates to an
              identified or identifiable individual.
            </li>
            <li>
              <strong>Service:</strong> Refers to the website.
            </li>
            <li>
              <strong>Service Provider:</strong> Any natural or legal person who
              processes data on behalf of the Company.
            </li>
            <li>
              <strong>Third-party Social Media Service:</strong> Any website or
              social network website through which a user can log in or create
              an account to use the service.
            </li>
            <li>
              <strong>Usage Data:</strong> Data collected automatically,
              generated by the use of the service or from the service
              infrastructure itself.
            </li>
            <li>
              <strong>Website:</strong> Refers to RATAN MATKA, accessible from
              [Website].
            </li>
            <li>
              <strong>You:</strong> The individual accessing or using the
              service, or the company or other legal entity on behalf of which
              such individual is accessing or using the service.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="text-xl font-semibold mt-4">
            Types of Data Collected
          </h3>
          <p className="mt-2">
            <strong>Personal Data:</strong> While using our service, we may ask
            you to provide us with certain personally identifiable information,
            including but not limited to:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
          </ul>
          <p className="mt-2">
            <strong>Usage Data:</strong> Usage Data is collected automatically
            when using the service and may include:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-2">
            <li>Your Device’s IP address</li>
            <li>Browser type and version</li>
            <li>Pages of our service that you visit</li>
            <li>Time and date of your visit</li>
            <li>Time spent on those pages</li>
            <li>Unique device identifiers</li>
            <li>Other diagnostic data</li>
          </ul>
          <p className="mt-2">
            <strong>Information from Third-Party Social Media Services:</strong>{" "}
            We allow you to create an account and log in through the following
            Third-party Social Media Services:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-2">
            <li>Google</li>
            <li>Facebook</li>
            <li>Twitter</li>
            <li>LinkedIn</li>
          </ul>
          <p className="mt-2">
            If you decide to register through or grant us access to a
            Third-party Social Media Service, we may collect personal data
            associated with that account, such as your name, email address,
            activities, or contact list.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">
            Tracking Technologies and Cookies
          </h2>
          <p className="mt-4">
            We use Cookies and similar tracking technologies to track activity
            on our service and store certain information. The technologies we
            use may include:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-2">
            <li>
              <strong>Cookies or Browser Cookies:</strong> A small file placed
              on your device. You can instruct your browser to refuse all
              Cookies or indicate when a Cookie is being sent. If you do not
              accept Cookies, some parts of our service may not be usable.
            </li>
            <li>
              <strong>Web Beacons:</strong> Small electronic files that permit
              the Company to count users who have visited certain pages or
              opened an email.
            </li>
          </ul>
          <p className="mt-4">
            We use both session and persistent Cookies for the purposes outlined
            below:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-2">
            <li>
              <strong>Necessary / Essential Cookies:</strong> Session Cookies
              that help authenticate users and prevent fraudulent use of
              accounts.
            </li>
            <li>
              <strong>Cookies Policy / Notice Acceptance Cookies:</strong>{" "}
              Persistent Cookies that identify if users have accepted the use of
              cookies.
            </li>
            <li>
              <strong>Functionality Cookies:</strong> Persistent Cookies that
              remember your preferences.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Use of Your Personal Data</h2>
          <p className="mt-4">
            The Company may use Personal Data for various purposes, including:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-2">
            <li>To provide and maintain our service.</li>
            <li>To manage your account and registration.</li>
            <li>For the performance of a contract.</li>
            <li>To contact you with updates, offers, and other information.</li>
            <li>To manage your requests.</li>
            <li>For business transfers.</li>
            <li>
              For other purposes such as data analysis and service improvement.
            </li>
          </ul>
          <p className="mt-4">
            We may share your personal information in certain situations,
            including with service providers, for business transfers, with
            affiliates, business partners, and other users, or with your
            consent.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">
            Retention of Your Personal Data
          </h2>
          <p className="mt-4">
            We will retain your Personal Data only for as long as necessary for
            the purposes set out in this Privacy Policy. We will also retain
            Usage Data for internal analysis purposes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">
            Transfer of Your Personal Data
          </h2>
          <p className="mt-4">
            Your information may be transferred to and maintained on computers
            located outside your jurisdiction where data protection laws may
            differ. Your consent to this Privacy Policy followed by your
            submission of such information represents your agreement to that
            transfer.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Delete Your Personal Data</h2>
          <p className="mt-4">
            You have the right to delete or request assistance in deleting your
            Personal Data. You may update, amend, or delete your information by
            signing in to your account or contacting us.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">
            Disclosure of Your Personal Data
          </h2>
          <p className="mt-4">
            The Company may disclose your Personal Data under certain
            circumstances, including business transactions, legal requirements,
            and other legal obligations.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">
            Security of Your Personal Data
          </h2>
          <p className="mt-4">
            We strive to use commercially acceptable means to protect your
            Personal Data but cannot guarantee its absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Children&apos;s Privacy</h2>
          <p className="mt-4">
            Our service does not address anyone under the age of 13. We do not
            knowingly collect personal information from anyone under 13. If you
            are a parent or guardian aware that your child has provided us with
            Personal Data, please contact us.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Links to Other Websites</h2>
          <p className="mt-4">
            Our service may contain links to other websites. We have no control
            over and assume no responsibility for the content, privacy policies,
            or practices of any third-party sites or services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">
            Changes to this Privacy Policy
          </h2>
          <p className="mt-4">
            We may update our Privacy Policy from time to time and will notify
            you of any changes by posting the new Privacy Policy on this page.
            You are advised to review this Privacy Policy periodically for any
            changes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Contact Us</h2>
          <p className="mt-4">
            If you have any questions about this Privacy Policy, you can contact
            us by visiting this page on our website:{" "}
            <Link href="http://www.ratanmatkas.com" className="text-blue-500">
              www.ratanmatkas.com
            </Link>
          </p>
        </section>
      </div>
      <div className="text-center py-16">
        <Link
          href="/"
          title="Page not found link"
          className="rounded-md bg-transparent border-solid border border-white px-6 py-2 cursor-pointer transition duration-500 hover:bg-gray-800"
          style={{ fontSize: "1rem", margin: "0, auto", width: "10rem" }}
        >
          Back to home
        </Link>
      </div>
      <Footer />
    </div>
  );
}
